@startuml Casos_de_Uso_Geral
title Diagrama Geral de Casos de Uso — GoTicket

left to right direction
skinparam packageStyle rectangle
skinparam actorStyle awesome

actor "Funcionário" as Funcionario
actor "Funcionário Autorizado" as FuncionarioAuth

FuncionarioAuth --|> Funcionario

rectangle "Sistema GoTicket" {
    usecase "UC01: Cadastrar Evento" as UC01
    usecase "UC02: Cadastrar Setores e Lotes" as UC02
    usecase "UC03: Realizar Venda Presencial" as UC03
    usecase "UC04: Cadastrar Participante" as UC04
    usecase "UC05: Emitir Comprovante / Ingresso Local" as UC05
    usecase "UC06: Cancelar Ingresso" as UC06
    usecase "UC07: Gerar Relatório" as UC07
    usecase "UC08: Utilizar Ingresso" as UC08
    usecase "Autenticar Usuário" as UC_Login
}

Funcionario --> UC_Login
Funcionario --> UC01
Funcionario --> UC02
Funcionario --> UC03
Funcionario --> UC07
Funcionario --> UC08

FuncionarioAuth --> UC06

UC03 ..> UC04 : <<include>>
UC03 ..> UC05 : <<include>>

@enduml
