db.url=jdbc:postgresql://localhost:5433/eventgo_db
db.user=postgres
db.password=postgres
db.schema=eventgo
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.idleTimeout=30000
db.pool.connectionTimeout=10000
